### ISSUE TITLE
Saving/Serialization options

### ISSUE THREAD

**Issue by phoeft670** [rleap-project/dlplan#49]
It would be nice to have the ability to save and load dlplan information between runs. 

Currently the strips domains need to be re-parsed when using dlplan for both feature generation and evaluation, which often happens in different codebases and/or programming languages. 

I see two ways to archive that:  
 - Direct Serialization of dlplan classes 
 -  Adding a storage format for annotated atoms, predicates (fluid vs static) and dlplan formulas

**Comment by drexlerd** [comment]
I think this is a great feature when working on both sides: python and c++.
Let's say we did something on the python side that we want to use on the c++ side.

In the case of policies, we provide methods for writing and reading to and from files. Can be made much easier with serialization because we currently have to reinitialize all the other parts, i.e., VocabularyInfo, InstanceInfo from scratch before reading policies from files.

The files must not be readable in my opinion, so binary serialization should be fine. I am not exactly sure how to ensure that all pointers are set correctly. I can imagine one needs to have a class that stores everything that should be serialized to get the pointers correctly after deserialization.

**Comment by jendrikseipp** [comment]
Instead of binary serialization, we might want to simply support reading string representations of features. But now that I'm thinking about it, this should already be possible, right? So from my point of view, no extra code is needed: we can already do the expensive feature generation once in Python, write all features to disk, and read them in C++.

**Comment by drexlerd** [comment]
Yes, that is possible already but what Paul suggests is to get completely rid of having to reinitialize the other parts to be able to reparse the features. Of course, this only works properly on the promise that the same grounding mechanisms were used, i.e., same naming conventions to have correct mappings, but that's what we usually do.

Example: Let's say you learn a `dlplan.Policy` in the python pipeline. Currently, to be able to use it in a c++ planner it is necessary to reinitialize VocabularyInfo + reading policy from file + providing function to map planner states to dlplan states.

Will more convenient to have just a single function call to deserialize + a function to map planner states to dlplan states. So, it will remove some boilerplate code that the user has to write. Maybe also less error prone.

**Comment by drexlerd** [comment]
I don't know what structures Paul wants to reuse in a simpler way. Probably it is just the SyntacticElementFactory since InstanceInfo differs from training and testing.

**Comment by phoeft670** [comment]
I was thinking about everything that is necessary to evaluate either formulas or policies so at least the VocabularyInfo or the SyntacticElementFactory, but additionally being able to load InstanceInfos one by one would also make a lot of use cases easier in my opinion.
So something like the string representation for formulas for SyntacticElementFactories and InstanceInfos in individual files would already do the job. For examply by, as mentioned, storing the static vs fluid classification for predicates and atoms alongside them.

**Comment by drexlerd** [comment]
There should be libraries to serialize a whole class with all members to a binary file. I remember that in the software praktikum we had to serialize/deserialize and game state and it was just a library call. Inventing readable string representations add a lot of writing and parsing code that must be adapted if things change in the code which can be quite annoying. We don't want all parts to be readable and there is already code for generating string representations of the parts that we want to read.

**Comment by jendrikseipp** [comment]
I still don't see a real benefit, only potential downsides, since binary formats are quite brittle. They work best if the format never changes, which is not the case for us, I think. Since we have to store the information about available predicates, atoms and states somewhere anyway, and we want to do that in plain text (for inspection and for Git), we might as well read from those files.

**Comment by drexlerd** [comment]
Serialization/Deserialization is still a missing part to be able to well-design separated pipeline steps in, for instance, a learning pipeline.

I have looked a bit more into serialization/deserialization. There are no circular dependencies in DLPlan which makes deserialization easy. To get shared ownership correct, one probably has to pass an object to each deserialize function that contains all previously constructed elements. With a common interface, we can provide both, binary and human-readable serialization and there are many header-only serialization libraries out there to keep external dependencies small.

**Comment by drexlerd** [comment]
I have looked further into this since because I want to improve the development phase of learning algorithms. It is often time consuming to regenerate the state spaces when restarting the learning pipeline. Therefore I added a simple API call that @phoeft670 suggested following the first approach using Boost. Boost is very powerful and can handle up to circular object graphs. Very little code was needed, see here: https://github.com/rleap-project/dlplan/blob/serialization/src/serialization/serialization.cpp

**Comment by drexlerd** [comment]
I started to realize that it is best to be able to serialize the whole state of the library, i.e., all objects that were created by the user. For this purpose I refactored the API to use a bunch of unordered_maps for all relevant classes (still incomplete).
